name: SQL_basic_internal
description: ''
version: 0.0.1
author: sony@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/sql_joob:
    name: sql_joob
    description: ''
    fabricUID: 102
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-09-01 08:29:18'
    author: sony@prophecy.io
functions:
  author: null
  createdAt: '2023-09-01 08:26:05'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer_dataset:
    name: customer_dataset
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/customer_dataset.sql
    - .prophecy/ide/models/customer_dataset.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-09-01 08:26:24'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/customer_seed:
    name: customer_seed
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - seeds/customer_seed.csv
    createdAt: '2023-09-01 08:26:33'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2023-09-01 08:26:05'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
