name: Trino_project
description: uidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfvuidfgkjsgdfksjfhksjfhsfkjhgsfkjhfgkjsfgksjfvghksjfvghkjfvhkdjfv
version: 0.0.1
author: jrohit+e2e@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/trino_job:
    name: trino_job
    description: ''
    fabricUID: 10920
    scheduler:
      MWAA: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-09-12 11:35:00'
    author: jrohit+e2e@prophecy.io
  jobs/Composer_trino_job:
    name: Composer_trino_job
    description: ''
    fabricUID: 10773
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-09-13 08:15:38'
    author: jrohit+e2e@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
functions:
  author: null
  createdAt: '2023-09-08 12:08:28'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer_model:
    name: customer_model
    schema:
      providerType: Trino
      fields:
      - name: FIRST_NAME
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/customer_model.sql
    - .prophecy/ide/models/customer_model.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-09-08 12:09:19'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/customer_seed:
    name: customer_seed
    schema:
      providerType: Trino
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/customer_seed.csv
    createdAt: '2023-09-08 12:08:56'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: jrohit+e2e@prophecy.io
  createdAt: '2023-09-08 12:08:28'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
