name: DeletePipFlow
description: ''
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: deletepipflow
  parentArtefactID: abhishekse2etestsprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-07-25 06:33:59'
pipelines:
  pipelines/P1:
    name: P1
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-25 06:33:59'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/P2:
    name: P2
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-25 06:34:10'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-07-25 06:33:59'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
