---
version: 2
sources:
- name: "hive_metastore.qa_database"
  database: "hive_metastore"
  schema: "qa_database"
  config:
    enabled: true
  tables:
  - name: "customer"
    columns:
    - name: "C_CUSTOMER_SK"
      dataType:
        type: "Decimal"
    - name: "C_CUSTOMER_ID"
      dataType:
        type: "String"
    - name: "C_CURRENT_CDEMO_SK"
      dataType:
        type: "Decimal"
    - name: "C_CURRENT_HDEMO_SK"
      dataType:
        type: "Decimal"
    - name: "C_CURRENT_ADDR_SK"
      dataType:
        type: "Decimal"
    - name: "C_FIRST_SHIPTO_DATE_SK"
      dataType:
        type: "Decimal"
    - name: "C_FIRST_SALES_DATE_SK"
      dataType:
        type: "Decimal"
    - name: "C_SALUTATION"
      dataType:
        type: "String"
    - name: "C_FIRST_NAME"
      dataType:
        type: "String"
    - name: "C_LAST_NAME"
      dataType:
        type: "String"
    - name: "C_PREFERRED_CUST_FLAG"
      dataType:
        type: "String"
    - name: "C_BIRTH_DAY"
      dataType:
        type: "Decimal"
    - name: "C_BIRTH_MONTH"
      dataType:
        type: "Decimal"
    - name: "C_BIRTH_YEAR"
      dataType:
        type: "Decimal"
    - name: "C_BIRTH_COUNTRY"
      dataType:
        type: "String"
    - name: "C_LOGIN"
      dataType:
        type: "String"
    - name: "C_EMAIL_ADDRESS"
      dataType:
        type: "String"
    - name: "C_LAST_REVIEW_DATE"
      dataType:
        type: "String"
  - name: "orders"
    columns:
    - name: "ID"
      dataType:
        type: "Decimal"
    - name: "USER_ID"
      dataType:
        type: "Decimal"
    - name: "ORDER_DATE"
      dataType:
        type: "Date"
    - name: "STATUS"
      dataType:
        type: "String"
  - name: "orders_dataset_db_1"
    columns:
    - name: "order_id"
      dataType:
        type: "Bigint"
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "order_status"
      dataType:
        type: "String"
    - name: "order_category"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "amount"
      dataType:
        type: "Double"
