name: Python
description: ''
version: 0.0.1
author: jrohit@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: python
  parentArtefactID: jrohitprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-07-17 07:20:19'
pipelines:
  pipelines/PythonPipeline:
    name: PythonPipeline
    description: ''
    author: jrohit@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-17 07:20:19'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-07-17 07:20:19'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
