name: Test-Project
description: ''
version: 0.0.1
author: jrohit@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testproject
  parentArtefactID: jrohitprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-11-27 09:30:14'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: jrohit@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-27 09:30:14'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-11-27 09:30:14'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.0.7
    isDefault: true
    author: null
    createdAt: '2023-11-27 09:29:57'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-11-27 09:29:57'
pipelineConfigurations: {}
