name: EM_Test_bug
description: ''
version: 0.0.1
author: jrohit+e2e@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: emtestbug
  parentArtefactID: emenabledteam
  buildSystem: wheel
  author: null
  createdAt: '2024-01-11 06:55:12'
pipelines:
  pipelines/Pipeline:
    name: Pipeline
    description: ''
    author: jrohit+e2e@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-01-11 06:55:12'
    datasets:
      inputs:
      - datasets/qa_database_test_uc_seed_1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/qa_database_test_uc_seed_1:
    name: qa_database_test_uc_seed_1
    description: ''
    author: jrohit+e2e@prophecy.io
    createdAt: '2024-01-11 07:44:43'
    mode: batch
    physicalDatasets:
      dbx_uc:
        fabricId: 8598
        datasetType: Database
        description: ''
        author: jrohit+e2e@prophecy.io
        createdAt: '2024-01-11 07:44:43'
templates: {}
jobs:
  jobs/Databricks_Job:
    name: Databricks_Job
    description: ''
    fabricUID: 8598
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small_job
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-01-25 09:10:18'
    author: jrohit+e2e@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-11 06:55:12'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.1.2
    isDefault: true
    author: null
    createdAt: '2024-01-18 11:47:38'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-01-11 06:55:02'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
