WITH ORDERS AS (

  SELECT * 
  
  FROM {{ source('QA_DATABASE.QA_SCHEMA', 'ORDERS') }}

),

CUSTOMER_1 AS (

  SELECT * 
  
  FROM {{ source('QA_DATABASE.QA_SCHEMA', 'CUSTOMER') }}

),

by_CUSTOMER_ID AS (

  SELECT 
    CUSTOMER_1.FIRST_NAME AS FIRST_NAME,
    CUSTOMER_1.LAST_NAME AS LAST_NAME,
    CUSTOMER_1.PHONE AS PHONE,
    CUSTOMER_1.EMAIL AS EMAIL,
    CUSTOMER_1.COUNTRY_CODE AS COUNTRY_CODE,
    CUSTOMER_1.ACCOUNT_OPEN_DATE AS ACCOUNT_OPEN_DATE,
    CUSTOMER_1.ACCOUNT_FLAGS AS ACCOUNT_FLAGS,
    ORDERS.CUSTOMER_ID AS CUSTOMER_ID,
    ORDERS.COUPON_AMOUNT AS COUPON_AMOUNT,
    ORDERS.CREDIT_CARD_AMOUNT AS CREDIT_CARD_AMOUNT,
    ORDERS.ORDER_ID AS ORDER_ID,
    ORDERS.STATUS AS STATUS,
    ORDERS.BANK_TRANSFER_AMOUNT AS BANK_TRANSFER_AMOUNT,
    ORDERS.ORDER_DATE AS ORDER_DATE,
    ORDERS.GIFT_CARD_AMOUNT AS GIFT_CARD_AMOUNT,
    ORDERS.AMOUNT AS AMOUNT
  
  FROM ORDERS
  INNER JOIN CUSTOMER_1
     ON ORDERS.CUSTOMER_ID = CUSTOMER_1.CUSTOMER_ID

)

SELECT *

FROM by_CUSTOMER_ID
