name: Snowflake_Project_external
description: ''
version: v1
author: jrohit+e2e@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/Airflow253:
    name: Airflow253
    description: ''
    fabricUID: 10795
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-06-04 09:39:26'
    author: jrohit+e2e@prophecy.io
    models: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-04 09:29:04'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer_model:
    name: customer_model
    schema:
      providerType: Snowflake
      fields:
      - name: FIRST_NAME
        dataType:
          type: String
      - name: LAST_NAME
        dataType:
          type: String
      - name: PHONE
        dataType:
          type: String
      - name: EMAIL
        dataType:
          type: String
      - name: COUNTRY_CODE
        dataType:
          type: String
      - name: ACCOUNT_OPEN_DATE
        dataType:
          type: Date
      - name: ACCOUNT_FLAGS
        dataType:
          type: String
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: COUPON_AMOUNT
        dataType:
          type: Number
      - name: CREDIT_CARD_AMOUNT
        dataType:
          type: Number
      - name: ORDER_ID
        dataType:
          type: Number
      - name: STATUS
        dataType:
          type: String
      - name: BANK_TRANSFER_AMOUNT
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: GIFT_CARD_AMOUNT
        dataType:
          type: Number
      - name: AMOUNT
        dataType:
          type: Number
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/customer_model.sql
    - .prophecy/ide/models/customer_model.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-04 09:29:36'
  .prophecy/metadata/sqlmodels/customers_by_country:
    name: customers_by_country
    schema:
      providerType: Snowflake
      fields:
      - name: LAST_NAME
        dataType:
          type: String
      - name: FIRST_NAME
        dataType:
          type: String
      - name: FULL_NAME
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/customers_by_country.sql
    - .prophecy/ide/models/customers_by_country.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-04 09:33:41'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/customer_seed:
    name: customer_seed
    schema:
      providerType: Snowflake
      fields: []
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/customer_seed.csv
    createdAt: '2024-06-04 09:29:47'
sqlSources:
  .prophecy/metadata/sqlsources/QA_DATABASE_QA_SCHEMA:
    name: QA_DATABASE.QA_SCHEMA
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-06-04 09:32:24'
    tables:
    - name: CUSTOMER
      schema:
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FIRST_NAME
          dataType:
            type: String
        - name: LAST_NAME
          dataType:
            type: String
        - name: PHONE
          dataType:
            type: String
        - name: EMAIL
          dataType:
            type: String
        - name: COUNTRY_CODE
          dataType:
            type: String
        - name: ACCOUNT_OPEN_DATE
          dataType:
            type: Date
        - name: ACCOUNT_FLAGS
          dataType:
            type: String
      description: Customer data including their personal information, contact details,
        account details, and account flags. This dataset provides insights into customer
        profiles and account information.
      author: jrohit+e2e@prophecy.io
      createdAt: '2024-06-04 09:32:24'
    - name: ORDERS
      schema:
        providerType: snowflake
        fields:
        - name: ORDER_ID
          dataType:
            type: Number
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: ORDER_DATE
          dataType:
            type: Date
        - name: STATUS
          dataType:
            type: String
        - name: CREDIT_CARD_AMOUNT
          dataType:
            type: Number
        - name: COUPON_AMOUNT
          dataType:
            type: Number
        - name: BANK_TRANSFER_AMOUNT
          dataType:
            type: Number
        - name: GIFT_CARD_AMOUNT
          dataType:
            type: Number
        - name: AMOUNT
          dataType:
            type: Number
      description: null
      author: jrohit+e2e@prophecy.io
      createdAt: '2024-06-04 09:32:32'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: jrohit+e2e@prophecy.io
  createdAt: '2024-06-04 09:29:04'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
