name: TestPipelineMerge
description: ''
version: 0.0.1
author: jrohit+e2e@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testpipelinemerge
  parentArtefactID: jrohite2eprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-07-25 07:20:11'
pipelines:
  pipelines/P22:
    name: P22
    description: ''
    author: jrohit+e2e@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-25 07:20:19'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-07-25 07:20:11'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
