name: SQL_HOTFIX_TESTING_DB_2
description: ''
version: 0.0.1
author: sony@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 102
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-09-08 07:35:25'
    author: sony@prophecy.io
functions:
  author: null
  createdAt: '2023-09-08 07:34:08'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer_model:
    name: customer_model
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/customer_model.sql
    - .prophecy/ide/models/customer_model.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-09-08 07:34:44'
sqlMacros:
  .prophecy/metadata/sqlmacros/generic_round:
    name: generic_round
    macroType: expression
    description: null
    author: sony@prophecy.io
    files:
    - macros/generic_round.sql
    - .prophecy/ide/macros/generic_round.json
    createdAt: '2023-09-08 07:38:38'
  .prophecy/metadata/sqlmacros/select_distinct_colums:
    name: select_distinct_colums
    macroType: query
    description: null
    author: sony@prophecy.io
    files:
    - macros/select_distinct_colums.sql
    - .prophecy/ide/macros/select_distinct_colums.json
    - macros/macros.yml
    createdAt: '2023-09-08 07:39:56'
sqlSeeds:
  .prophecy/metadata/sqlseeds/new_seed:
    name: new_seed
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - seeds/new_seed.csv
    createdAt: '2023-09-08 07:34:27'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2023-09-08 07:34:08'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
