name: newSQL
description: ''
version: v2
author: jrohit@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/jobs:
    name: jobs
    description: ''
    fabricUID: 49
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-10-11 12:12:35'
    author: jrohit@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
functions:
  author: null
  createdAt: '2023-10-11 12:11:49'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customer:
    name: customer
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit@prophecy.io
    files:
    - models/customer.sql
    - .prophecy/ide/models/customer.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-10-11 12:23:26'
  .prophecy/metadata/sqlmodels/test:
    name: test
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit@prophecy.io
    files:
    - models/test.sql
    - .prophecy/ide/models/test.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-10-11 12:12:07'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/seed:
    name: seed
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit@prophecy.io
    files:
    - seeds/seed.csv
    createdAt: '2023-10-11 12:12:19'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: jrohit@prophecy.io
  createdAt: '2023-10-11 12:11:49'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
