name: Scala_basic_external_git
description: ''
version: 0.0.1
author: jrohit+e2e@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scala_basic_external_git
  parentArtefactID: jrohite2eprophecy.io_team
  buildSystem: maven
  author: null
  createdAt: '2023-09-06 06:19:43'
pipelines:
  pipelines/NewPipeline:
    name: NewPipeline
    description: ''
    author: jrohit+e2e@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-09-06 06:19:43'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-09-06 06:19:43'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
