name: Spark
description: ''
version: 0.0.1
author: jrohit@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: spark
  parentArtefactID: jrohitprophecy.io_team
  buildSystem: maven
  author: null
  createdAt: '2023-07-17 06:32:53'
pipelines:
  pipelines/TestPipeline:
    name: TestPipeline
    description: ''
    author: jrohit@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-07-17 06:32:53'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-07-17 06:32:53'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
