name: JDBC_gem_Migration_Scala
description: ''
version: 0.0.1
author: jrohit@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: jdbcgemmigrationscala
  parentArtefactID: jrohitprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2024-01-17 11:05:38'
pipelines:
  pipelines/FirstPipeline:
    name: FirstPipeline
    description: ''
    author: jrohit@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-01-17 11:05:38'
    datasets:
      inputs:
      - datasets/JDBC_Gem_source_1
      - datasets/JDBC_SOURCE_2
      - datasets/Source_3
      - datasets/source6
      - datasets/source_4
      - datasets/source_7
      outputs:
      - datasets/TARGET_2
      - datasets/Target_1
      - datasets/Target_6
      - datasets/target_3
      - datasets/target_4
      - datasets/target_7
    subgraphs: []
    dependencies: {}
datasets:
  datasets/JDBC_Gem_source_1:
    name: JDBC_Gem_source_1
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-17 12:08:05'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-17 12:08:06'
  datasets/JDBC_SOURCE_2:
    name: JDBC_SOURCE_2
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 13:13:26'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 13:13:26'
  datasets/Target_1:
    name: Target_1
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 16:45:13'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 16:45:13'
  datasets/TARGET_2:
    name: TARGET_2
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 16:55:16'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 16:55:16'
  datasets/Source_3:
    name: Source_3
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 16:59:02'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 16:59:02'
  datasets/target_4:
    name: target_4
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 17:16:33'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 17:16:33'
  datasets/source_4:
    name: source_4
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 17:27:22'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 17:27:22'
  datasets/target_3:
    name: target_3
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-24 17:29:34'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-24 17:29:34'
  datasets/source_5:
    name: source_5
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-25 03:58:07'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-25 03:58:07'
  datasets/source6:
    name: source6
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-25 04:40:39'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-25 04:40:39'
  datasets/Target_6:
    name: Target_6
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-25 04:42:29'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-25 04:42:29'
  datasets/source_7:
    name: source_7
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-25 04:45:59'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-25 04:45:59'
  datasets/target_7:
    name: target_7
    description: ''
    author: jrohit@prophecy.io
    createdAt: '2024-01-25 04:48:18'
    mode: batch
    physicalDatasets:
      databricks_fabric_13_3_LTS:
        fabricId: 370
        datasetType: Warehouse
        description: ''
        author: jrohit@prophecy.io
        createdAt: '2024-01-25 04:48:19'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.4
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-17 11:05:38'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '39':
    projectUID: 39
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_39.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-01-17 11:05:18'
  '40':
    projectUID: 40
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_40.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-01-17 11:05:18'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
